name: 'Email Addresses in Comments Alerts'
description: 'Check for emails in Github issues and comments'
outputs:
  emails: # id of output
    description: 'Email addresses found in comment'
runs:
  using: 'node12'
  main: 'dist/index.js'
