on:
  issue_comment:
    types: [created, edited]
  issues:
    types: [opened, edited]
jobs:
  find_emails:
    runs-on: ubuntu-latest
    name: Check for emails in issue comments
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Scan comment
      id: scan
      uses: ./ # Uses an action in the root directory
    - name: Update issue to include email addresses alert
      if: ${{ steps.scan.outputs.emails != '' }}
      run: |
        jq -nc '{"body": "${{ steps.scan.outputs.emails }}"}' | \
        curl -sL  -X POST -d @- \
        -H "Content-Type: application/json" \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"