on:
  issue_comment:
    types: [created, edited]
  issues:
    types: [opened, edited]
jobs:
  env:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
  find_emails:
    runs-on: ubuntu-latest
    name: Check for emails in issue comments
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Hello world action step
      uses: ./ # Uses an action in the root directory
    - name: Update issue to include email addresses alert
      run: echo "The time was ${{ steps.hello.outputs.time }}"